install:
- ps: >-
    Install-PackageProvider -Name NuGet -Force
    Install-Module -Name PSScriptAnalyzer -Force
    Install-Module -Name -verbose Pester -Force

build: off
test_script:
- ps: >-
    import-module pester;
    start-sleep -seconds 2;
    Get-Module Pester;
    Get-Module PSMarkdown;
    write-verbose "invoking pester";
    $res = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru;
    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml));
    if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."};
    if($res.FailedCount -eq 0 -and $APPVEYOR_REPO_COMMIT_MESSAGE -match '^.*dep-psgallery$'){
        write-host "Module would now be deployed to the psgallery" -forgroundcolor green;
    }else{
        write-host "Module would not be deployed to the psgallery" -forgroundcolor Yellow;
    }
